name: Generate Hashes

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hash-grab
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i
      - run: node updateFromScRepo.js
      - run: node updateFromGithub.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: node updateFromDiscord.js
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      - name: Commit report
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "Update hashes" || :
          git push
