name: Deploy container to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: "read"
  packages: "write"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./java-host/Dockerfile
          context: ./java-host

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Deploy App 1
        uses: azure/webapps-deploy@v2
        with:
          app-name: ratrater1
          publish-profile: ${{ secrets.PUBLISH_PROFILE_1 }}
          images: "ghcr.io/${{ env.REPO }}:${{ github.sha }}"
      - name: Deploy App 2
        uses: azure/webapps-deploy@v2
        with:
          app-name: ratrater2
          publish-profile: ${{ secrets.PUBLISH_PROFILE_2 }}
          images: "ghcr.io/${{ env.REPO }}:${{ github.sha }}"
      - name: Deploy App 3
        uses: azure/webapps-deploy@v2
        with:
          app-name: ratrater3
          publish-profile: ${{ secrets.PUBLISH_PROFILE_3 }}
          images: "ghcr.io/${{ env.REPO }}:${{ github.sha }}"
      - name: Deploy App 4
        uses: azure/webapps-deploy@v2
        with:
          app-name: ratrater4
          publish-profile: ${{ secrets.PUBLISH_PROFILE_4 }}
          images: "ghcr.io/${{ env.REPO }}:${{ github.sha }}"
